In [12]:
import pandas as pd

nft1 = pd.read_csv('NFT1.csv')
nft2 = pd.read_csv('NFT2.csv')
nft1.head()

                                          nft  number  Unnamed: 2
0  0x7bfee91193d9df2ac0bfe90191d40f23c773c060       9         NaN
1  0x49e96e255ba418d08e66c35b588e2f2f3766e1d0       5         NaN
2  0x4d34b72da483a73eb7113cf5d02b34e627296553       5         NaN
3  0xc24cd18b563bf4f58bbdd959f453cc25374836ed       4         NaN
4  0xe8f379c8014745a71e566eb9d0e5692a67081a45       3         NaN

In [13]:
nft1 = set(nft1['nft'].to_list())
len(nft1)

1389

In [14]:
nft2.head()

                                    user_link  Unnamed: 1
0  0x7bfee91193d9df2ac0bfe90191d40f23c773c060         NaN
1  0x562e4e25f4bb991c66cdb74c4af3957e0ffd3f89         NaN
2  0x8d84d5b85bfe2a269afa305afdf422a39927adc3         NaN
3  0x995d1899cbbc2bc92cca6f264334a15b1d75d928         NaN
4  0x60559b4cc92292b589ded75295f5331adcc69e04         NaN

In [15]:
nft2 = set(nft2['user_link'].to_list())
len(nft2)

1426

In [19]:
nft1 - nft2

{'0x000000000a38444e0a6e37d3b630d7e855a7cb13',
 '0x001b0458a438238f8869465acd9e97fe4de17b1a',
 '0x0022e00560d1fd651e71df08d98edc028e3baf1a',
 '0x006f81c9126d4e6fdcd39a4e24e9210a9bb3ecf1',
 '0x008d63fab8179ee0ae2082bb57c72ed0c61f990f',
 '0x0098377e5028f52b5fc038dd1775f859e8cfb564',
 '0x00ab97c782c661fb3d08c96dce06176938101211',
 '0x00b3230e7215e3dfb85f576326630ad24e89848e',
 '0x00d1b620029471617c3df4c81001dcc8162d3db2',
 '0x00e66bc44e2b0a88c9293bb2ca8d0b01cea1e82c',
 '0x00ff6b7d26407a46af2b631b4fa452a036d027e5',
 '0x01413153821946871f742490937946e5992ed40b',
 '0x06a84a5364af1f043b77e10bce2568e94af76d5a',
 '0x1254958bd5073c6b238e516298f0c48f6f60a78e',
 '0x12e6314c1eb68e413b20c0e67dab98807fdc4df6',
 '0x139791013f6dcc26f4052e6a7b8ed50099e7d15b',
 '0x1402de507719544277be20043b6c6717f38d362e',
 '0x18821c4afdb4acfe6df9daa69754718c9f2ce7ac',
 '0x188f2447f7517f46a6c617aecf950b740cd8eb98',
 '0x19f928a2ba7fe4745f05dcd3f2e89bc2584f931e',
 '0x1e8bc13fb0478c5843d66ee3caa71ff8dfaa3c14',
 '0x214d7e35cb265c416629d209e35fed58e252afce',
 '0x3c6dfb5d608c4849d289d81d8bfccbd48d86d0a8',
 '0x4b4ed195f54edba8fddb4600dd29e16b3912aa5e',
 '0x4bbb94f56b5f138ad759da8e0e6f8102843f24a8',
 '0x55a781d9c65561933aec6d4eee74a20edfce51fb',
 '0x5f2cbc511ef0a92a473943672a7a97028ababc29',
 '0x60b0fba5b289800743b35ad8be16cddede2bd67f',
 '0x6281559f11b64180700b3ebb3796f5da2e678f2f',
 '0x68f0ae07b4b7dd71bb9c4dfbfad483cc462061b6',
 '0x80835bb6000ca3bf97da32233c5818652d8bf495',
 '0x88b835e481cabef3c7c35e4007b2f413aab7755f',
 '0x8fa45aa6f62ab1e00912016dfb51ecfcee452b34',
 '0x9e46cc3bb7c6c1e691c812b986f465a8ddb12823',
 '0xa5b02095aec69ef5b9308e1eecabb81c55ca0686',
 '0xa811c417506720d045523c76cbf448407301a595',
 '0xace7f306bdae84179cce3a6f7c2a0233299267ab',
 '0xbb770160549b62cf19aa05d67130a7a3554dde3f',
 '0xbded327a145b4703300e10204e6d180e1a15c844',
 '0xd5557a1dcb5d9a34939528cbdea5128e1a6a1c04',
 '0xdbf12acb93d8fd935d37314f325be5a49be8e49e',
 '0xea080de78b140031ce75f6cd7dd7e2cab854e240',
 '0xec7836bdcc7481d3450e3f22fd9a3ae928d753bf',
 '0xeecc0e50b64cb4a67d98cb5fd1bd7e87b6c1bd47',
 '0xf61c7b8debf1e6f76f02a2e68129e0ffbe6f2db0'}

In [12]:
from web3 import Web3
from eth_account import Account
import secrets
import time


# 连接到以太坊网络（例如Infura或本地节点）
infura_url = "https://bartio.rpc.berachain.com/"
w3 = Web3(Web3.HTTPProvider(infura_url))

# 检查连接状态
if w3.is_connected():
    print("Connected to Ethereum network")
else:
    print("Failed to connect to Ethereum network")

private_key_new_wallet = "0x96305205daabc4a0a97cd483b9f0668759551107240665a772511a57655528b0"
new_wallet = Account.from_key(private_key_new_wallet)
# 获取新钱包的地址
new_wallet_address = new_wallet.address

# 合约地址（假设你已经有了合约地址）
contract_address = "0xfc5e3743E9FAC8BB60408797607352E24Db7d65E"

# 合约方法的 MethodID (faucet 函数)
faucet_method_id = "0xde5f72fd"

nonce = w3.eth.get_transaction_count(new_wallet_address)

# 构造交易
tx = {
'nonce': nonce,
'to': contract_address,
'value': 0,  # 调用合约方法不需要发送 ETH
'gas': 200000,  # 估算合适的 Gas limit
'maxPriorityFeePerGas': w3.to_wei('2', 'gwei'),  # 设置优先费
'maxFeePerGas': w3.to_wei('2', 'gwei'),  # 设置最大 Gas 费用
'data': faucet_method_id,  # 指定调用的合约方法
'chainId': 80084,  # 主网为 1；测试网取决于网络，例如 Rinkeby 为 4
}

# 对交易进行签名
signed_tx = w3.eth.account.sign_transaction(tx, private_key_new_wallet)

# 发送交易
tx_hash = w3.eth.send_raw_transaction(signed_tx.rawTransaction)

# 输出交易哈希
print(f"Transaction Hash: {w3.to_hex(tx_hash)}")

Connected to Ethereum network
Transaction Hash: 0x0cfe4c4bc681b887a1ef611c3d63a97f9b8a3aa051aed9c955bb809472b0b63f